name: steps examples

on:
   push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:            
      - name: Configuração do Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Verifica versão
        run: node --version
